### ISSUE TITLE
Windows 8 Pro x64 support?

### ISSUE THREAD

**Issue by XLDS** [Thulinma/ndsplus#1]
Hello, is there anyway you could help me get this working on Windows 8? I'd greatly appreciate it.

**Comment by Thulinma** [comment]
There's nothing in the code for ndsplus that, in theory, won't work in Windows 8.
Assuming you first compile/install the Windows version of libusb ( http://www.libusb.org/wiki/windows_backend ) you should be able to then compile ndsplus. I would suggest either MingW or Cygwin, as those are probably most easy to get to play nicely with this project.

Feel free to ask more specific questions if you have them, I'll see what I can do to help.

PS: Doesn't the official software work in W8? I've never tried (not a big Windows user, heh), just assumed it would work...

**Comment by XLDS** [comment]
Wow, thanks for the quick reply, that surprised me. (I kinda figured it would be a few days or never... thanks a lot again.)

In Windows 8 you have to restart your PC with advanced start up "Disable Driver Signature Enforcement" enabled.
http://www.craftedge.com/tutorials/driver_install_windows8/driver_install_win8.html

But once installing the INFs even with it disabled, Windows 8 hasn't been able to detect the adapter.

I'm actually fairly new to compiling stuff, I'll try and figure it out. Thanks again so much for the quick reply.

I greatly appreciate your time Thulinma.

**Comment by Thulinma** [comment]
Yeah, with me it's usually either a near-instant reply... or it'll take months ;-)

Good luck, let me know if you run into any problems. In theory, it should work completely driver-less using this method, but I haven't tried anything on Windows myself. Would be interesting to see the results, at least! If it works well, feel free to send over your compiled binaries and I'll add them to the downloads page for other Windows users.

**Comment by Thulinma** [comment]
Assuming everything works, since no more reply came. :-)
