### ISSUE TITLE
Korg DS10+ not working

### ISSUE THREAD

**Issue by mikaelgu** [Thulinma/ndsplus#10]
The Korg DS10+ card is not working. Here is the output with --debug.

Cheers!
/Mikael

0000: 03 aa 55 aa  55 aa 00 01                                                      ..U.U...
NDS Adapter+ firmware version 256 detected.
0000: 44 53 31 30  50 4c 55 53  00 00 00 00  56 4b 47 45  58 4a 02 00  08 00 00 00  DS10PLUS....VKGEXJ......
0018: 00 00 00 00  03 00 00 00  00 40 00 00  00 48 00 02  00 40 00 02  d8 5d 05 00  .........@...H...@...]..
0030: 00 b4 05 00  00 00 38 02  00 00 38 02  84 8f 02 00  00 44 08 00  c7 21 00 00  ......8...8......D...!..
0048: 00 66 08 00  a0 0f 00 00  00 9e 05 00  20 00 00 00  00 00 00 00  00 00 00 00  .f.......... ...........
0060: 57 66 41 00  f8 08 18 08  00 76 08 00  b5 4d 7e 0d  a8 4e 00 02  d4 03 38 02  WfA......v...M~..N....8.
0078: 00 00 00 00  00 00 00 00  00 a4 71 00  00 40 00 00  b0 0f 00 00  d4 05 00 00  ..........q..@..........
0090: 0f 00 0f 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ........................
00a8: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ........................
00c0: 24 ff ae 51  69 9a a2 21  3d 84 82 0a  84 e4 09 ad  11 24 8b 98  c0 81 7f 21  $..Qi..!=........$.....!
00d8: a3 52 be 19  93 09 ce 20  10 46 4a 4a  f8 27 31 ec  58 c7 e8 33  82 e3 ce bf  .R..... .FJJ.'1.X..3....
00f0: 85 f4 df 94  ce 4b 09 c1  94 56 8a c0  13 72 a7 fc  9f 84 4d 73  a3 ca 9a 61  .....K...V...r....Ms...a
0108: 58 97 a3 27  fc 03 98 76  23 1d c7 61  03 04 ae 56  bf 38 84 00  40 a7 0e fd  X..'...v#..a...V.8..@...
0120: ff 52 fe 03  6f 95 30 f1  97 fb c0 85  60 d6 80 25  a9 63 be 03  01 4e 38 e2  .R..o.0.....`..%.c...N8.
0138: f9 a2 34 ff  bb 3e 03 44  78 00 90 cb  88 11 3a 94  65 c0 7c 63  87 f0 3c af  ..4..>.Dx.....:.e.|c..<.
0150: d6 25 e4 8b  38 0a ac 72  21 d4 f8 07  56 cf 74 39  00 00 00 00  00 00 00 00  .%..8..r!...V.t9........
0168: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ........................
0180: 81 85 89 8d  80 84 88 8c  90 94 98 9c  80 84 88 8c  90 94 98 9c  00 00 00 00  ........................
0198: 40 37 c0 07  00 37 40 07  00 30 40 00  40 37 c0 07  00 37 40 07  0f 00 00 03  @7...7@..0@.@7...7@.....
01b0: 02 00 00 00  00 00 00 00  06 00 00 00  00 00 00 00  00 30 78 00  00 00 00 00  .................0x.....
01c8: 00 00 40 02  74 2e 00 00  00 70 78 00  44 04 03 03  00 00 e8 02  f8 70 04 00  ..@.t....px.D........p..
01e0: 00 40 00 00  00 0c 6f 00  00 30 78 00  00 b4 04 00  00 4c 6f 00  00 44 02 00  .@....o..0x......Lo..D..
01f8: 00 90 71 00  20 12 00 00                                                      ..q. ...
Card title: DS10PLUS
Card ID: VKGE
Card size: 32 MiB
It looks like you got a card that I don't know how to handle. Please run me with --debug and post the output as an issue on github - thanks!

**Comment by Thulinma** [comment]
This is caused because your adapter is running firmware version 256 - you need at least version 304 for the program to function, currently.
There are plans to include upgrade support in the program, but that hasn't been finished yet.

If you use a VM or regular windows machine to run the firmware updater, your adapter should work correctly afterwards under linux/mac using this program, too.

Good luck!

**Comment by mikaelgu** [comment]
Everything works perfectly after the update, thanks!
