### ISSUE TITLE
Is it possible to restore eShop save data to 3DS card?

### ISSUE THREAD

**Issue by trueinsider** [Thulinma/ndsplus#12]
Let's say I have two Mario Kart 7 games, one of which was downloaded from eShop and another bought at retail store. Now, my eShop version has so much progress which I want to transfer over 3DS Card of Mario Kart 7. I know 3DS has function which allows to backup save data to SD. Then I can retrieve it from SD using PC. Question is: would it be possible to restore such save data to 3DS Card?

**Comment by Thulinma** [comment]
As far as I'm aware, the savedata backup is encrypted with your 3DS's unique keys. Unless you decrypt the backup first, you won't be able to do anything with it except for restoring it through the on-3DS menus.

In other words: though technically possible, this is generally not do-able for a normal user.
