### ISSUE TITLE
Pokemon X and Y Firmware Update Needed!!! 

### ISSUE THREAD

**Issue by flippinpnoi** [Thulinma/ndsplus#14]
Pokemon X and Y are not compatible with firmware 3.05. Please upload a new firmware update as soon as possible! I only bought this hardware for the sole purpose of backing up my save files and I was very disappointed that it does not support my newly bought Pokemon X.

**Comment by Thulinma** [comment]
I'm just a user myself here - and I completely agree.
I'm sure EMS already knows about this - I'll update the software with firmware-updating capabilities as soon as they release a new firmware.

**Comment by Thulinma** [comment]
Duplicate of #13
