### ISSUE TITLE
How do I use the software?

### ISSUE THREAD

**Issue by windie1** [Thulinma/ndsplus#15]
I have an updated NDS+. The software recognizes it, saves, logs out. I can't find the save file and how to I dump a file back into the cartridge?

**Comment by Thulinma** [comment]
Have you read the instructions here?
https://github.com/Thulinma/ndsplus#using-the-program

They explain it pretty well, I think. If anything about them is unclear, feel free to ask for clarification.

**Comment by windie1** [comment]
I can't type anything into the terminal.

**Comment by Thulinma** [comment]
Sounds like you might have open the wrong kind of terminal? There's not much I can do to help with that part, I'm afraid.

**Comment by windie1** [comment]
my-mac:~ fabio$ /Users/fabio/Downloads/ndsplus\ 3 ; exit;
NDS Adapter+ firmware version 301 detected.
Card title: POKEMON W
Card ID: IRAO
Card size: 256 MiB
Save: 512 KiB FLASH
logout

[Process completed]

I can type in a normal terminal window, but not in the NDS+ window.

**Comment by Thulinma** [comment]
Ah - I see the problem. You should first open a normal terminal windows and start the application from there. Don't let the application open it's own window.

**Comment by windie1** [comment]
Thank you! I can type the full commands now and it works!

**Comment by Thulinma** [comment]
Glad to hear it. Enjoy!
