### ISSUE TITLE
NDS Adapter Plus doesn't work on Windows 7 (64-bit)

### ISSUE THREAD

**Issue by ARevolution** [Thulinma/ndsplus#20]
I have the NDS Adapter Plus (#0907) and am downloaded NDS Adapter Plus v3.05. When I click to update the firmware to v3.05 I get a message that says "This upgrade program may damage your NDS Adapter! Please close other adapter file if it had been open!" I don't have any other EMS products running. There is an upgrade button, but the program won't allow me to click on it.
![untitled](https://cloud.githubusercontent.com/assets/12651818/7874539/d40b30e4-057e-11e5-89cd-814a7fcc9f72.png)

**Comment by Thulinma** [comment]
Hello! This isn't the place to find support for the adapter on Windows, as this is the Mac/Linux driver code only.
To get support for the Windows drivers, please contact EMS directly.
(I'm just a volunteer that wanted Linux support... I do not work for EMS)
