### ISSUE TITLE
NDS Adapter Plus mac

### ISSUE THREAD

**Issue by twelsh100** [Thulinma/ndsplus#24]
I cannot seem to get the adapter to work. This is what I am getting with the adapter plugged in.

Last login: Fri May 13 21:37:06 on console
Thomass-MacBook-Pro:~ twelsh$ /Users/twelsh/Downloads/ndsplus ; exit;
Could not find NDS Adapter+ - is it plugged in?
logout

[Process completed]

I also tried to use it in VirtualBox on XP but I could never upgrade to v3.05 and v3.03 was not able to read the card. Any help would be great.

**Comment by Thulinma** [comment]
That sounds like a permissions issue (e.g. your user is not allowed to access the device).
Unfortunately I'm not a Mac user myself, and can't really help much more than simply saying that. If there is a Mac equivalent to running something with elevated permission (like sudo or su on Linux) you might want to try that.

**Comment by twelsh100** [comment]
I just tried turning off the Mac equivalent of device driver signing, but that did not work. I also created a windows partition to see if it would work if I disabled the device driver signing. I did not work on XP,  7, 8, or 10. Any advice would be great.

**Comment by Thulinma** [comment]
This method doesn't use any drivers whatsoever - the application communicates directly with the device over libusb. So no amount of fiddling with driver signing settings will make any difference. :-) 
The problem really is access permission: it needs to have permission to reach arbitrary USB devices, and thus needs to be run from the equivalent of an administrator account. That goes for all operating systems.

**Comment by twelsh100** [comment]
Ok I just tried to do it as a root user on Mac and as an admin on my windows partition. I still got the same result. I was able to use Crossover to upgrade the firmware to v3.05, but when I tried to open the v3.03 exe I got this. 
<img width="413" alt="screen shot 2016-05-14 at 4 37 22 pm" src="https://cloud.githubusercontent.com/assets/19357258/15271199/456e0f80-19f2-11e6-9081-476c9989136b.png">

**Comment by Thulinma** [comment]
Is it possible your adapter itself is perhaps malfunctioning and/or broken?
If even the official software won't work with it anymore, I doubt this alternate driver will have more luck.
You might want to try listing the plugged-in USB devices and checking if the adapter's ID (4670:9394) shows up in there. If it doesn't show up as a device, no amount of software magic is going to make it work (because then it's a hardware problem). If it does show up, it should be possible to get it working.

**Comment by twelsh100** [comment]
Well sadly it looks like you're right. It did not show up as a listed device. Thanks for all the help.

**Comment by Thulinma** [comment]
I do believe EMS will exchange it for a working one if you send it back to them. At least, they did that when mine broke a few years back...

**Comment by twelsh100** [comment]
Oh thanks for letting me know, I'll try doing that. And thanks for helping me out, I appreciate it.

**Comment by Thulinma** [comment]
No problem. Good luck!
