### ISSUE TITLE
Unable to run Pokemon White

### ISSUE THREAD

**Issue by Diondelpino** [Thulinma/ndsplus#3]
Hi I'm hoping you can help me out I just bought a NDS Adaptor Plus, and I'm hoping to get it working on my Mac. I downloaded your software Ndsplus-mac.zip and tried running the Adaptor however it keeps displaying this info to me:
NDS Adapter+ firmware version 256 detected.
Card title: POKEMON W
Card ID: IRAO
Card size: 256 MiB
It looks like you got a card that I don't know how to handle. Please run me with --debug and post the output as an issue on github - thanks!
You wouldn't happen to know the solution to this problem do you?

**Comment by Thulinma** [comment]
Hey,

I've never been able to test the application on that firmware version...
Your best bet would be to update the firmware to the latest using a Windows machine and the official updater, then use my application to actually _use_ it on your Mac.
I'd like to add support for lower version firmwares, but it's not very high on my priorities list :-)
(And, as mentioned in issue #2, I hope to add firmware updating support to this application at some point, too!)

**Comment by Diondelpino** [comment]
Cool thank you for replying so fast. hmm now to find someone with a pc…

**Comment by Thulinma** [comment]
Ah, actually, using (and updating) the stick through VirtualBox works just fine, if you have that installed. Might be easier than finding a real Windows machine!

**Comment by Diondelpino** [comment]
Thank you again I'm going to give that a go

**Comment by Thulinma** [comment]
Closing for lack of reply - assuming problem was fixed - feel free to re-open if/as needed.
