### ISSUE TITLE
NDS Adaptor plus and WarioWare D.I.Y. do it yourself/Wario made in ore

### ISSUE THREAD

**Issue by lozaffo** [Thulinma/ndsplus#4]
I bought a NDS Adaptor plus without reading the whole Q&A session, so I didn't realized that there is a problem with WarioWare D.I.Y., which is the game I'm interested to work with.

Is there any possibility to fix this problem for this wonderfull product?

Thanks a lot,
lozaffo

**Comment by Thulinma** [comment]
You'll have to ask the people at EMS (I'm just another user that wrote mac/linux drivers for this device, because I needed them myself) - compatibility with cartridges is completely managed through device firmware updates, not software.
You can reach them at sales@hkems.com - good luck! :-)
