### ISSUE TITLE
DS Fake Games

### ISSUE THREAD

**Issue by zimfandelis** [Thulinma/ndsplus#6]
I just want ask does NDS™ Adaptor Plus  working with fake DS games? Asking because i just bought save dongle from http://www.r4i-sdhc.com/SaveDongle.asp and it working only with orginal games.
And my question if i will buy NDS™ Adaptor Plus  does it working with fake ds games?
Thank you Andrius.

**Comment by Thulinma** [comment]
I'm not an EMS employee (just a volunteer that maintains the OSX/Linux drivers), but in my experience the answer to your question is "Yes, but only if the fake card uses the same save chip as the original".
Hope that helps. So... the best I can tell you is maybe, depending on the game you're trying.
