### ISSUE TITLE
Animal Crossing New Leaf

### ISSUE THREAD

**Issue by thespillmonkey** [Thulinma/ndsplus#7]
Is ACNL going to be supported? As of now, it seems to simply lock up when the cart inserted.

**Comment by Thulinma** [comment]
The application only locks up when the device itself stops responding. This means that they will need to release an update for the device itself to get ACNL to work.

You'll have to ask EMS (sales@hkems.com) for an official statement on this - I only wrote the linux/mac driver, I don't have anything to do with device updates. :-)
