### ISSUE TITLE
NDS Adapter not working in Windows 8 64 bit (Problem not resolved)

### ISSUE THREAD

**Issue by ZephyrSonic** [Thulinma/ndsplus#9]
I just got your response and I have to open this thread since it's not resolved since you closed out the last one but this is what im getting when I try to install the drivers and Ive pointed it to the driver folder as well as disabling the signing enforcement and did the Driver Signature Enforcement Overrider and it still does it.

![nds adapter plus driver problems](https://f.cloud.github.com/assets/5395222/1098907/d9a62a16-172a-11e3-965e-d005d08ff47f.PNG)
![nds adapter plus driver problems2](https://f.cloud.github.com/assets/5395222/1098908/dcf5dd56-172a-11e3-9507-e45ca248ac98.PNG)

**Comment by Thulinma** [comment]
(You can actually re-open a closed issue - but sure.)

You shouldn't need to install any drivers - just keep it as "unknown device".
The ndsplus application works at a lower level and doesn't require the device to be recognized by the OS at all.

**Comment by ZephyrSonic** [comment]
It still won't read it. It just reads it as an unknown device and when I go into the program with the Cart inserted the boxes for Save and Import are greyed out still.

**Comment by Thulinma** [comment]
Sounds like you're using the official driver from EMS and not the ndsplus application that I wrote. I can only provide help with ndsplus - for the official EMS software you'll have to contact EMS themselves. :-) (they can be reached at sales@hkems.com )

**Comment by Thulinma** [comment]
Closing because of lack of further reply. Feel free to re-open as/if still needed.
